// lib/workoutConstants.ts

export const muscleGroupPools: Record<string, string[]> = {
  "only biceps": [
    "Dumbbell Bicep Curl",
    "Hammer Curl",
    "Barbell Curl",
    "Preacher Curl",
    "Concentration Curl",
    "EZ Bar Curl",
    "Spider Curl",
    "Cable Bicep Curl",
    "Incline Dumbbell Curl",
    "Zottman Curl",
  ],
  "only triceps": [
    "Tricep Pushdown",
    "Overhead Extension",
    "Skullcrushers",
    "Dips",
    "Close-Grip Bench Press",
    "Rope Pushdown",
    "Kickbacks",
    "Diamond Push-Ups",
    "Bench Dips",
    "French Press",
  ],
  "only legs": [
    "Barbell Back Squat",
    "Leg Press",
    "Romanian Deadlift",
    "Leg Extension",
    "Leg Curl",
    "Calf Raise",
    "Walking Lunges",
    "Hack Squat",
    "Bulgarian Split Squat",
    "Glute Bridge",
  ],
  "only quads": [
    "Hack Squat",
    "Leg Extension",
    "Front Squat",
    "Bulgarian Split Squat",
    "Goblet Squat",
    "Sissy Squat",
    "Step-Ups",
    "Cyclist Squat",
    "Leg Press (High Foot Placement)",
    "Quad Extension (Iso)",
  ],
  "only thighs": [
    "Sumo Squat",
    "Leg Press",
    "Inner Thigh Machine",
    "Lunges",
    "Hamstring Curl",
    "Good Mornings",
    "Stiff Leg Deadlift",
    "Hip Adduction",
    "Curtsy Lunges",
    "Glute-Ham Raise",
  ],
  "only chest": [
    "Bench Press",
    "Incline Dumbbell Press",
    "Chest Fly",
    "Push-Up",
    "Dips",
    "Decline Bench Press",
    "Cable Crossover",
    "Pec Deck",
    "Dumbbell Pullover",
    "Floor Press",
  ],
  "only back": [
    "Deadlift",
    "Pull-Up",
    "Barbell Row",
    "Lat Pulldown",
    "Seated Cable Row",
    "Face Pull",
    "T-Bar Row",
    "Single Arm Dumbbell Row",
    "Straight Arm Pulldown",
    "Reverse Fly",
  ],
  "only calves": [
    "Standing Calf Raise",
    "Seated Calf Raise",
    "Donkey Calf Raise",
    "Calf Press on Leg Press",
    "Single Leg Calf Raise",
    "Jump Rope",
    "Tibialis Raise",
  ],
  "only cardio": [
    "Treadmill Run",
    "Cycling",
    "Rowing Machine",
    "Elliptical",
    "Stair Climber",
    "Battle Ropes",
    "Assault Bike",
    "Swimming",
    "Jump Rope",
    "Burpees",
  ],
  "only hiit": [
    "Burpees",
    "Mountain Climbers",
    "Kettlebell Swings",
    "Jumping Lunges",
    "Battle Ropes",
    "Box Jumps",
    "Thrusters",
    "Sprints",
    "Plyo Push-ups",
    "Jump Squats",
  ],
  "only full body": [
    "Thrusters",
    "Clean and Press",
    "Deadlift",
    "Burpees",
    "Turkish Get-Up",
    "Kettlebell Snatch",
    "Bear Crawls",
    "Man-Makers",
    "Wall Balls",
    "Devil Press",
  ],
};

export const equipmentPlans: Record<string, string[]> = {
  "Build muscle": [
    "Barbell Back Squat",
    "Bench Press",
    "Romanian Deadlift",
    "Pull-Up",
    "Overhead Press",
    "Dumbbell Row",
    "Leg Press",
    "Incline Dumbbell Press",
    "Dips",
    "Lateral Raise",
  ],
  "Lose fat": [
    "Goblet Squat",
    "Dumbbell Bench Press",
    "Lat Pulldown",
    "Walking Lunge",
    "Seated Row",
    "Kettlebell Swing",
    "Bike Intervals",
    "Treadmill Incline Walk",
    "Mountain Climbers",
    "Plank",
  ],
  "Improve endurance": [
    "Bike Intervals",
    "Treadmill Incline Walk",
    "Rowing Machine",
    "Step-Ups",
    "Goblet Squat",
    "Dumbbell Push Press",
    "Plank",
    "Farmer Carry",
    "Wall Sits",
    "Box Steps",
  ],
  "Increase strength": [
    "Barbell Back Squat",
    "Deadlift",
    "Bench Press",
    "Overhead Press",
    "Barbell Row",
    "Split Squat",
    "Chin-Up",
    "Hip Thrust",
    "Farmer Carry",
    "Rack Pulls",
  ],
};

export const noEquipmentPlans: Record<string, string[]> = {
  "Build muscle": [
    "Push-Up",
    "Bulgarian Split Squat",
    "Bodyweight Row",
    "Pike Push-Up",
    "Glute Bridge",
    "Tempo Squat",
    "Plank",
    "Mountain Climbers",
    "Diamond Push-Ups",
    "Reverse Lunges",
  ],
  "Lose fat": [
    "Burpee",
    "Bodyweight Squat",
    "Alternating Lunge",
    "Push-Up",
    "Mountain Climbers",
    "Jumping Jacks",
    "High Knees",
    "Plank",
    "Plank Jacks",
    "Skaters",
  ],
  "Improve endurance": [
    "Jumping Jacks",
    "High Knees",
    "Mountain Climbers",
    "Bodyweight Squat",
    "Alternating Reverse Lunge",
    "Plank Shoulder Tap",
    "Walk/Jog Intervals",
    "Step-Ups",
    "Bear Crawl",
    "Flutter Kicks",
  ],
  "Increase strength": [
    "Decline Push-Up",
    "Bulgarian Split Squat",
    "Single-Leg Glute Bridge",
    "Pike Push-Up",
    "Tempo Squat",
    "Bodyweight Row",
    "Hollow Hold",
    "Side Plank",
    "Superman",
    "Wall Sit",
  ],
};
